title:              생각중
email:              jheun5@naver.com
description:        개발 블로그
author:             Eun JongHyeok
baseurl:            ""
url:                "https://jheun66.github.io"

# Social Profiles
twitter_username:   amos55606241
github_username:    jheun66
facebook_username:  amos.eun.73
instagram_username: jheun66 
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-T1H0RYSGS7 # out your google-analytics code
google_site_verification:   NFjrooIb0zLycxDgti6xtOkaLhYWvCAhYLDCsDf8sQI

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag
